#!/usr/bin/env bash

# bash completion for Node Version Manager (BEAMER)

if ! command -v beamer &> /dev/null; then
  return
fi

__beamer_generate_completion() {
  declare current_word
  current_word="${COMP_WORDS[COMP_CWORD]}"
  # shellcheck disable=SC2207
  COMPREPLY=($(compgen -W "$1" -- "${current_word}"))
  return 0
}

__beamer_commands() {
  declare current_word
  declare command

  current_word="${COMP_WORDS[COMP_CWORD]}"

  COMMANDS='
    help install uninstall use run exec
    alias unalias reinstall-packages
    current list ls list-remote ls-remote
    install-latest-npm
    cache deactivate unload
    version version-remote which'

  if [ ${#COMP_WORDS[@]} == 4 ]; then

    command="${COMP_WORDS[COMP_CWORD - 2]}"
    case "${command}" in
      alias) __beamer_installed_nodes ;;
    esac

  else

    case "${current_word}" in
      -*) __beamer_options ;;
      *) __beamer_generate_completion "${COMMANDS}" ;;
    esac

  fi
}

__beamer_options() {
  OPTIONS=''
  __beamer_generate_completion "${OPTIONS}"
}

__beamer_installed_nodes() {
  __beamer_generate_completion "$(beamer_ls) $(__beamer_aliases)"
}

__beamer_aliases() {
  declare aliases
  aliases=""
  if [ -d "${BEAMER_DIR}/alias" ]; then
    aliases="$(command cd "${BEAMER_DIR}/alias" && command find "${PWD}" -type f | command sed "s:${PWD}/::")"
  fi
  echo "${aliases} node stable unstable iojs"
}

__beamer_alias() {
  __beamer_generate_completion "$(__beamer_aliases)"
}

__beamer() {
  declare previous_word
  previous_word="${COMP_WORDS[COMP_CWORD - 1]}"

  case "${previous_word}" in
    use | run | exec | ls | list | uninstall) __beamer_installed_nodes ;;
    alias | unalias) __beamer_alias ;;
    *) __beamer_commands ;;
  esac

  return 0
}

# complete is a bash builtin, but recent versions of ZSH come with a function
# called bashcompinit that will create a complete in ZSH. If the user is in
# ZSH, load and run bashcompinit before calling the complete function.
if [[ -n ${ZSH_VERSION-} ]]; then
  # First calling compinit (only if not called yet!)
  # and then bashcompinit as mentioned by zsh man page.
  if ! command -v compinit > /dev/null; then
    autoload -U +X compinit && if [[ ${ZSH_DISABLE_COMPFIX-} = true ]]; then
      compinit -u
    else
      compinit
    fi
  fi
  autoload -U +X bashcompinit && bashcompinit
fi

complete -o default -F __beamer beamer
