#!/usr/bin/env bash

DIR="$(command cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

unset BEAMER_CD_FLAGS

# shellcheck disable=SC1090,SC1091
\. "$DIR/beamer.sh" --no-use

if [ -n "$BEAM_VERSION" ]; then
  nvm use "$BEAM_VERSION" > /dev/null || exit 127
elif ! nvm use >/dev/null 2>&1; then
  echo "No BEAM_VERSION provided; no .beamerrc file found" >&2
  exit 127
fi

exec "$@"
